### ISSUE TITLE
Lock view in iPhone SE

### ISSUE THREAD

**Issue by MaatheusGois** [yoxisem544/ScreenshotPreventing-iOS#7] opened 2022-12-10 05:24 UTC

**Comment by YaroslavReznichenko** [comment] 2023-04-27 09:42
Yes, I found this bug.

Need to add this line 

container.isUserInteractionEnabled = true -> line 82

in next code
<img width="811" alt="Знімок екрана 2023-04-27 о 12 35 58" src="https://user-images.githubusercontent.com/131962448/234824805-0536f747-4019-4402-b5c8-252b0c34090f.png">

**Comment by yoxisem544** [comment] 2023-04-27 14:32
Can you provide more information on how to reproduce this bug?

**Comment by YaroslavReznichenko** [comment] 2023-04-27 14:39
I reproduced it on simulator Iphone 11 or else does not matter but IOS 15.0 When IOS 16.2 for example everything is ok. I have table view which I need to hide from screenshots. So when I launch simulator with IOS 15.0 table view does not scrolling. I tried to add this line in your code and bug was fixed.

**Comment by yoxisem544** [comment] 2023-04-27 14:55
Did you use this view inside table view's cell?

**Comment by YaroslavReznichenko** [comment] 2023-04-27 14:59
No, I put whole table)
<img width="409" alt="Знімок екрана 2023-04-27 о 17 57 38" src="https://user-images.githubusercontent.com/131962448/234903055-bac97058-9c5f-4ea0-b4f0-8baf5548d8a1.png">

Also I have another view with gestures. Same problem -> no user interactionenabled

**Comment by yoxisem544** [comment] 2023-04-27 15:15
I think the problem is TextView's hidden container will takeover every touch event. So non of these touch events will be passed through responder chain. I will try to fix it, thank you for the information.

**Comment by YaroslavReznichenko** [comment] 2023-04-27 15:30
Thanks) Let me know when I can test it in my project please) And thank you for this framework!

**Comment by yoxisem544** [comment] 2023-04-27 16:17
Fixed in version 1.2.2. Please try it out.

**Closed as completed by yoxisem544** 2023-04-27 16:17 UTC

**Comment by YaroslavReznichenko** [comment] 2023-04-28 07:49
Works well) Thanks
